<?php
if (session_status() === PHP_SESSION_NONE) session_start();
if (empty($_SESSION['is_logged_in'])) { header('Location: ../connexion.php'); exit; }
if (($_SESSION['user_type'] ?? '') !== 'acheteur') { header('Location: dashboard.php'); exit; }
require_once __DIR__ . '/../models/select/CommandeSelect.php';
$user_id = (int) $_SESSION['user_id']; $user_type = 'acheteur';
$user_nom = $_SESSION['user_nom'] ?? ''; $user_prenom = $_SESSION['user_prenom'] ?? ''; $user_email = $_SESSION['user_email'] ?? '';
$commandes = CommandeSelect::getByAcheteur($user_id);
$stats = ['total'=>count($commandes),'attente'=>0,'livraison'=>0,'livree'=>0];
foreach($commandes as $c){if($c->statut_commande==='en_attente')$stats['attente']++;elseif($c->statut_commande==='en_livraison')$stats['livraison']++;elseif($c->statut_commande==='livree')$stats['livree']++;}
?>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mes commandes - Butembo Marché</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet"><style>
:root{--green:#2d6a4f;--bg:#f5f7f6;--surface:#fff;--text:#17202a;--muted:#64748b;--border:#e2e8f0;--soft:#f8fafc}html.dark{--bg:#0f172a;--surface:#1e293b;--text:#e2e8f0;--muted:#94a3b8;--border:#334155;--soft:#0f172a}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}.layout{display:flex;min-height:100vh}.sidebar{position:fixed;inset:0 auto 0 0;width:260px;padding:24px 16px;background:var(--surface);border-right:1px solid var(--border);display:flex;flex-direction:column}.brand{padding:0 12px 24px;color:var(--green);font-size:1.15rem;font-weight:800}.sidebar-nav{display:flex;flex-direction:column;gap:6px}.nav-label{padding:12px;color:#94a3b8;font-size:.72rem;text-transform:uppercase;font-weight:700}.nav-link{padding:11px 13px;border-radius:10px;color:var(--muted);text-decoration:none}.nav-link i{margin-right:9px}.nav-link:hover,.nav-link.active{background:var(--green);color:#fff}.profile{margin-top:auto;padding:16px 8px 0;border-top:1px solid var(--border)}.profile strong,.profile small{display:block}.profile small{color:var(--muted)}.main{margin-left:260px;width:calc(100% - 260px);padding:28px}.top{display:flex;justify-content:space-between;gap:15px;align-items:center}.actions{display:flex;gap:8px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:24px 0}.stat,.panel{background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:20px}.stat strong{display:block;font-size:1.7rem}.stat span,.muted{color:var(--muted)}.order{border:1px solid var(--border);border-radius:12px;padding:18px;margin-bottom:14px}.order-head{display:flex;justify-content:space-between;gap:12px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:16px 0}.label{font-size:.72rem;text-transform:uppercase;color:#94a3b8;font-weight:700}.badge-status{padding:6px 10px;border-radius:20px;font-size:.78rem;font-weight:700}.en_attente{background:#fef3c7;color:#92400e}.en_livraison{background:#dbeafe;color:#1d4ed8}.livree{background:#dcfce7;color:#166534}.annulee{background:#fee2e2;color:#991b1b}.detail{background:var(--soft);padding:13px;border-radius:9px}.products{margin-top:10px;padding-top:10px;border-top:1px solid var(--border)}@media(max-width:850px){.sidebar{position:static;width:100%}.layout{display:block}.main{margin:0;width:100%;padding:16px}.stats,.grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.stats,.grid{grid-template-columns:1fr}.order-head{display:block}}
</style></head><body><div class="layout"><aside class="sidebar"><div class="brand"><i class="bi bi-basket2-fill"></i> Butembo Marché</div><?php require __DIR__.'/partials/sidebar-nav.php'; ?><div class="profile"><strong><?=htmlspecialchars($user_prenom.' '.$user_nom)?></strong><small><?=htmlspecialchars($user_email)?></small><a href="../models/logout.php" class="btn btn-sm btn-outline-danger mt-3"><i class="bi bi-box-arrow-right"></i> Déconnexion</a></div></aside>
<main class="main"><header class="top"><div><h1 class="h3 mb-1">Mes commandes</h1><p class="muted mb-0">Consultez vos achats et leur livraison</p></div><div class="actions"><a href="../index.php" class="btn btn-success"><i class="bi bi-bag-plus"></i> Commander</a><button class="btn btn-outline-secondary" onclick="toggleTheme()" title="Mode sombre"><i id="themeIcon" class="bi bi-moon-stars"></i></button></div></header>
<section class="stats"><div class="stat"><strong><?=$stats['total']?></strong><span>Total</span></div><div class="stat"><strong><?=$stats['attente']?></strong><span>En attente</span></div><div class="stat"><strong><?=$stats['livraison']?></strong><span>En livraison</span></div><div class="stat"><strong><?=$stats['livree']?></strong><span>Livrées</span></div></section><section class="panel">
<?php if(!$commandes):?><div class="text-center py-5 muted"><i class="bi bi-bag-x fs-1 d-block mb-2"></i>Vous n’avez encore passé aucune commande.<br><a href="../index.php" class="btn btn-success mt-3">Découvrir les produits</a></div><?php endif;?>
<?php foreach($commandes as $c):$labels=['en_attente'=>'En attente','en_livraison'=>'En livraison','livree'=>'Livrée','annulee'=>'Annulée'];$lignes=CommandeSelect::getLignesCommande($c->id);?>
<article class="order"><div class="order-head"><div><strong>#<?=htmlspecialchars($c->numero_commande)?></strong><div class="muted small"><?=date('d/m/Y à H:i',strtotime($c->date_commande))?></div></div><span class="badge-status <?=htmlspecialchars($c->statut_commande)?>"><?=$labels[$c->statut_commande]??$c->statut_commande?></span></div><div class="grid"><div><div class="label">Montant</div><strong><?=number_format((float)$c->montant_total,0,',',' ')?> FC</strong></div><div><div class="label">Articles</div><strong><?=(int)$c->nb_produits?></strong></div><div><div class="label">Paiement</div><strong><?=htmlspecialchars($c->mode_paiement?:'Non renseigné')?></strong></div><div><div class="label">Suivi</div><strong><?=htmlspecialchars($c->code_suivi?:'Pas encore assigné')?></strong></div></div><div class="detail"><div class="label">Adresse de livraison</div><?=htmlspecialchars($c->adresse_livraison?:'Non renseignée')?><?php if($c->instructions_livraison):?><div class="muted small"><?=htmlspecialchars($c->instructions_livraison)?></div><?php endif;?><div class="products"><?php foreach($lignes as $ligne):?><div class="d-flex justify-content-between"><span><?=htmlspecialchars($ligne->produit_nom)?></span><strong><?=htmlspecialchars($ligne->quantite.' '.$ligne->unite_mesure)?></strong></div><?php endforeach;?></div></div></article><?php endforeach;?></section></main></div>
<script>function icon(){document.getElementById('themeIcon').className=document.documentElement.classList.contains('dark')?'bi bi-sun':'bi bi-moon-stars'}function toggleTheme(){document.documentElement.classList.toggle('dark');localStorage.setItem('theme',document.documentElement.classList.contains('dark')?'dark':'light');icon()}if(localStorage.getItem('theme')==='dark'||(!localStorage.getItem('theme')&&matchMedia('(prefers-color-scheme:dark)').matches))document.documentElement.classList.add('dark');icon()</script></body></html>
